### PR TITLE
Fix #103

### LINKED ISSUE #103: Code coverage token secret
@baggepinnen 
https://discourse.julialang.org/t/psa-new-version-of-codecov-action-requires-additional-setup/109857

It seems that we now need to add add the codecov token in the repo secret with `codecov/codecov-action@v4`. The badge is not updated at all since this update. Are you able to do that on you side? I don't have access to the repo secrets.

### PR DESCRIPTION
**Pull request by baggepinnen**
The secret is already in place, so I think this should be enough

### CODE REVIEW

**Comment by francis-gagnon** [comment]
Ok I will try to merge it but it seems that key is wrong or something else, here in red:
image

**Comment by franckgaga** [comment]
Ok I wil try to merge it but it seems that the key is wrong or something else. Here, in red:
image

**Comment by baggepinnen** [comment]
I updated the token just in case it had expired or something, I'll retrigger the workflow to see if it worked

**Comment by francis-gagnon** [comment]
Yes it works now, good job!

**Comment by franckgaga** [comment]
Yes it works now, good job!

**Pull request merged**
